// src/app/components/footer/footer.component.ts
import { Component } from "@angular/core"
import { CommonModule } from "@angular/common"

@Component({
  selector: "app-footer",
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer class="footer">
      <div class="container">
        <div class="footer-content">
          <div class="footer-logo">
            <img src="assets/logo.png" alt="CODFY Logo" height="60">
            <p>TRAZABILIDAD E INNOVACIÓN</p>
          </div>
          
          <div class="footer-links">
            <div class="link-column">
              <h3>Productos</h3>
              <a href="https://notamaestro.com" target="_blank">NotaMaestro</a>
              <a href="https://ampirux.com" target="_blank">Ampirux</a>
              <a href="https://toolveris.com" target="_blank">Toolveris</a>
            </div>
            
            <div class="link-column">
              <h3>Empresa</h3>
              <a href="#nosotros">Sobre Nosotros</a>
              <a href="#productos">Productos</a>
              <a href="#desarrollo">App a tu medida</a>
            </div>
          </div>
        </div>
        
        <div class="footer-bottom">
          <p>&copy; {{ currentYear }} CODFY. Todos los derechos reservados.</p>
          <div class="legal-links">
            <a href="/terminos">Términos y Condiciones</a>
          </div>
        </div>
      </div>
    </footer>
  `,
  styles: [
    `
    .footer {
      background-color: #100f1f;
      color: white;
      padding: 70px 0 20px;
    }
    
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 20px;
    }
    
    .footer-content {
      display: flex;
      flex-wrap: wrap;
      gap: 40px;
      justify-content: space-between;
      margin-bottom: 50px;
    }
    
    .footer-logo {
      flex: 1;
      min-width: 200px;
    }
    
    .footer-logo p {
      margin-top: 10px;
      font-size: 0.9rem;
      color: #aaa;
    }
    
    .footer-links {
      display: flex;
      flex-wrap: wrap;
      gap: 40px;
    }
    
    .link-column {
      min-width: 150px;
    }
    
    .link-column h3 {
      font-size: 1.2rem;
      margin-bottom: 20px;
      color: #429cd8;
    }
    
    .link-column a {
      display: block;
      color: #aaa;
      margin-bottom: 10px;
      text-decoration: none;
      transition: color 0.3s;
    }
    
    .link-column a:hover {
      color: white;
    }
    
    .footer-bottom {
      padding-top: 20px;
      border-top: 1px solid rgba(255, 255, 255, 0.1);
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      align-items: center;
      gap: 20px;
    }
    
    .footer-bottom p {
      font-size: 0.9rem;
      color: #aaa;
    }
    
    .legal-links {
      display: flex;
      gap: 20px;
    }
    
    .legal-links a {
      font-size: 0.9rem;
      color: #aaa;
      text-decoration: none;
      transition: color 0.3s;
    }
    
    .legal-links a:hover {
      color: white;
    }
    
    @media (max-width: 768px) {
      .footer-content, .footer-bottom {
        flex-direction: column;
        text-align: center;
      }
      
      .footer-links {
        justify-content: center;
      }
    }
  `,
  ],
})
export class FooterComponent {
  currentYear = new Date().getFullYear()
}

// src/components/layout/footer.tsx
import Link from "next/link";
import Image from "next/image";
import { MapPin, Mail, Phone } from "lucide-react";
import { SITE, CONTACT, SOCIALS, FOOTER_LINKS } from "@/lib/constants";
import { FacebookIcon, InstagramIcon, TikTokIcon, WhatsAppIcon } from "@/components/shared/brand-icons";

export function Footer() {
  return (
    <footer className="relative overflow-hidden bg-codfy-ink text-white/80">
      <div className="absolute inset-0 gradient-mesh-codfy opacity-30" />
      <div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="grid gap-12 lg:grid-cols-4">
          <div className="space-y-5 lg:col-span-1">
            <Link href="/" className="inline-block">
              <Image src="/assets/logo.png" alt={SITE.name} width={140} height={48} className="h-10 w-auto" />
            </Link>
            <p className="text-sm text-white/60 max-w-xs">
              Software para la transformación digital. Trazabilidad e innovación al servicio de tu negocio.
            </p>
            <div className="flex items-center gap-3">
              <a
                href={SOCIALS.facebook}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Facebook"
                className="flex h-9 w-9 items-center justify-center rounded-full bg-white/5 text-white/70 transition-all hover:bg-codfy hover:text-white"
              >
                <FacebookIcon className="h-4 w-4" />
              </a>
              <a
                href={SOCIALS.instagram}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Instagram"
                className="flex h-9 w-9 items-center justify-center rounded-full bg-white/5 text-white/70 transition-all hover:bg-codfy hover:text-white"
              >
                <InstagramIcon className="h-4 w-4" />
              </a>
              <a
                href={SOCIALS.tiktok}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="TikTok"
                className="flex h-9 w-9 items-center justify-center rounded-full bg-white/5 text-white/70 transition-all hover:bg-codfy hover:text-white"
              >
                <TikTokIcon className="h-4 w-4" />
              </a>
              <a
                href={SOCIALS.whatsapp}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="WhatsApp"
                className="flex h-9 w-9 items-center justify-center rounded-full bg-white/5 text-white/70 transition-all hover:bg-codfy hover:text-white"
              >
                <WhatsAppIcon className="h-4 w-4" />
              </a>
            </div>
          </div>

          <div>
            <h4 className="mb-4 text-sm font-semibold uppercase tracking-wider text-white">Productos</h4>
            <ul className="space-y-3 text-sm">
              {FOOTER_LINKS.products.map((link) => (
                <li key={link.href}>
                  <Link href={link.href} className="text-white/60 transition-colors hover:text-white">
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="mb-4 text-sm font-semibold uppercase tracking-wider text-white">Empresa</h4>
            <ul className="space-y-3 text-sm">
              {FOOTER_LINKS.company.map((link) => (
                <li key={link.href}>
                  <Link href={link.href} className="text-white/60 transition-colors hover:text-white">
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="mb-4 text-sm font-semibold uppercase tracking-wider text-white">Contacto</h4>
            <ul className="space-y-3 text-sm text-white/60">
              <li className="flex items-start gap-2">
                <MapPin className="mt-0.5 h-4 w-4 shrink-0 text-codfy" />
                <span>{CONTACT.address}</span>
              </li>
              <li className="flex items-center gap-2">
                <Phone className="h-4 w-4 shrink-0 text-codfy" />
                <a href={`tel:${CONTACT.phoneRaw}`} className="transition-colors hover:text-white">
                  {CONTACT.phone}
                </a>
              </li>
              <li className="flex items-center gap-2">
                <Mail className="h-4 w-4 shrink-0 text-codfy" />
                <a href={`mailto:${CONTACT.email}`} className="transition-colors hover:text-white">
                  {CONTACT.email}
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-8 text-xs text-white/40 sm:flex-row">
          <p>
            © {new Date().getFullYear()} {SITE.legalName}. Todos los derechos reservados.
          </p>
          <Link href="/terminos" className="transition-colors hover:text-white/80">
            Términos y Condiciones
          </Link>
        </div>
      </div>
    </footer>
  );
}
